name: Build Flatpak

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  flatpak:
    name: Build Flatpak
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-23.08
      options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: fossflow.flatpak
          manifest-path: org.fossflow.FossFLOW.yml
          cache-key: flatpak-builder-${{ github.sha }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: fossflow-flatpak
          path: fossflow.flatpak
